config/routes.rb
Rails.application.routes.draw do
  root to: "cafes#index"
  resources :cafes, only: %i(index)
  namespace :admin do
    resources :cafes, only: %i(new create)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
  validates:address, presence: true, length: {maximum: 50}
  validates:name, presence: true, length: {maximum: 40}
end

app/models/map_query.rb
class MapQuery

  def initialize(cafe_param)
    @cafe_param = cafe_param
  end

  def uri
    address = URI.encode_www_form({address: @cafe_param})
    URI.parse("https://maps.googleapis.com/maps/api/geocode/json?address=#{address}&key=#{ENV["MAP_API_KEY"]}")
  end

  def status
    api_response = Net::HTTP.get_response(uri)
    response_body = JSON.parse(api_response.body)
    response_body["status"]
  end

  def result
    api_response = Net::HTTP.get_response(uri)
    response_body = JSON.parse(api_response.body)
    response_body["results"][0]["geometry"]["location"]
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

end

app/controllers/admin/cafes_controller.rb
class Admin::CafesController < Admin::BaseController
  def new
    @cafe = Cafe.new
  end

  def create
    @result = MapQuery.new(params[:cafe]).result
    @status = MapQuery.new(params[:cafe]).status

    @cafe = Cafe.new(
      name: cafe_params["name"],
      address: cafe_params["address"],
      latitude: @result["lat"],
      longitude: @result["lng"]
    )

    if @cafe.save
      flash[:notice] = "保存しました"
      redirect_to cafes_path
    elsif @status != "OK"
      flash.now[:danger] = "保存に失敗しました"
      render action: :new
    else
      flash.now[:danger] = "保存に失敗しました"
      render action: :new
    end
  end
  
  private
  
    def cafe_params
      params.require(:cafe).permit(:name, :address, :latitude, :longitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  def index
    @all_cafe_position = Cafe.all.pluck(:latitude, :longitude).to_json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cafes/new.html.slim
.admin
  h1 管理者画面
  h2 自家焙煎のコーヒーショップの住所と名前を登録してください
  br
  = form_with model:@cafe, url: admin_cafes_path, local: true do |f|
    .form-group
      p 店舗名を入力
      = f.text_field :name, placeholder: "XX COFFEE ROASTER", class: "form-control"
      br
      p 住所を入力
      = f.text_field :address, placeholder: "東京都港区芝公園4-2−8", class: "form-control"
      br
      = f.submit "登録する", class: "btn btn-primary"

  = flash[:danger]

app/views/cafes/index.html.slim
.alert-success
  - if flash[:notice]
    = flash[:notice]

#roaster
  h1 コーヒーロースター一覧
  #map 
  #marker-data data-position=@all_cafe_position

  =javascript_pack_tag 'home/index'

  script src="https://maps.googleapis.com/maps/api/js?key=#{ENV['MAP_API_KEY']}&callback"

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | ROASTERS MAP
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ROASTERS MAP
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .header
      = image_tag "logo.png", size: "100x100"
      .header-flex 自家焙煎のコーヒーショップを紹介します
      = link_to "管理者画面", new_admin_cafe_path, class: "btn btn-info"
    = yield